version: "3"
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    user: root
    env_file:
      - docker-compose.env
    volumes:
      - .:/srv/affordable-housing-monitoring:cached
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      private:

  db:
    image: postgres
    networks:
      private:
    restart: on-failure

networks:
  private:
